const path = require("path");

function diagramPage(root, tree, truncated) {
  const name = path.basename(root);
  const safeTree = JSON.stringify(tree).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
  const safeName = name.replace(/[&<>"']/g, char => ({"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"}[char]));
  return `<!doctype html><!-- REGAIN_TREE_V1 -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeName} · ReGain</title>
<style>
:root{font-family:Inter,Segoe UI,system-ui,sans-serif;color-scheme:dark;background:#0d1721;color:#ecf6f8;--panel:#192a37;--edge:#35586b;--muted:#a4becd;--accent:#70d7dc;--accent2:#9cb5ff}
:root[data-theme="light"]{color-scheme:light;background:#f4f8fa;color:#172a36;--panel:#fff;--edge:#c9dce5;--muted:#56707d;--accent:#087b85;--accent2:#525da5}
*{box-sizing:border-box}body{margin:0;padding:clamp(20px,4vw,48px)}main{max-width:1300px;margin:auto}.eyebrow{color:var(--accent);font-size:.75rem;font-weight:800;letter-spacing:.15em;text-transform:uppercase}h1{font-size:clamp(2rem,4vw,3.3rem);margin:12px 0 10px}p{color:var(--muted);line-height:1.55}.intro{max-width:780px}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:25px 0 13px}input{min-width:min(420px,100%);flex:1;background:var(--panel);color:inherit;border:1px solid var(--edge);border-radius:11px;padding:12px 14px;font:inherit}input:focus{outline:2px solid var(--accent)}.crumbs{display:flex;gap:7px;flex-wrap:wrap;margin:18px 0 22px}.crumbs button{border:0;background:transparent;color:var(--accent);cursor:pointer;font:inherit;padding:3px}.crumbs button:hover{text-decoration:underline}.crumbs span{color:var(--muted)}.map{display:grid;grid-template-columns:minmax(220px,300px) minmax(0,1fr);gap:clamp(25px,5vw,75px);position:relative;align-items:start;min-height:270px}.edges{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible;z-index:0}.focus,.children{z-index:1;position:relative}.children{display:grid;grid-template-columns:repeat(auto-fill,minmax(205px,1fr));gap:13px}.card{background:var(--panel);border:1px solid var(--edge);border-radius:15px;box-shadow:0 12px 30px #0002;padding:17px;min-width:0}.focus .card{border-color:var(--accent);position:sticky;top:20px}.tag{font-size:.71rem;letter-spacing:.11em;text-transform:uppercase;color:var(--accent);font-weight:750}.card h2,.card h3{overflow-wrap:anywhere;margin:12px 0 8px}.card h2{font-size:1.35rem}.card h3{font-size:1rem}.card p{font-size:.85rem;margin:0 0 13px}.actions{display:flex;flex-wrap:wrap;gap:8px}.actions button,.pager button{font:inherit;border:1px solid var(--edge);background:transparent;border-radius:8px;color:var(--accent);padding:7px 9px;cursor:pointer}.actions button:hover,.pager button:hover{background:color-mix(in srgb,var(--accent) 13%,transparent)}.actions .learn{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 9%,transparent)}.pager{display:flex;gap:12px;align-items:center;margin:18px 0;color:var(--muted)}#status{color:var(--accent);min-height:26px;font-size:.9rem}.empty{border:1px dashed var(--edge);border-radius:12px;padding:28px}.note{font-size:.8rem;margin-top:30px}@media(max-width:700px){.map{grid-template-columns:1fr;gap:20px}.edges{display:none}.focus .card{position:static}}
</style></head><body><main><div class="eyebrow">ReGain · project diagram</div><h1>${safeName}</h1><p class="intro">Explore the project from modules to files and functions. <strong>Explore</strong> moves deeper into the diagram; <strong>Learn</strong> creates a walkthrough for that branch and colors its source lines.</p><div class="toolbar"><input id="search" type="search" placeholder="Find a module, file, or function…" aria-label="Find a module, file, or function"></div><nav class="crumbs" id="crumbs" aria-label="Project path"></nav><div id="status" role="status"></div><div class="map" id="map"><svg class="edges" id="edges" aria-hidden="true"></svg><div class="focus" id="focus"></div><div><div class="children" id="children"></div><div class="pager" id="pager"></div></div></div><p class="note">${truncated ? "The project index reached its size limit. Narrow the workspace if a module is missing." : "The diagram comes from local source files. Colors are a draft until their reasons are reviewed against project behavior."}</p></main>
<script>
const tree=${safeTree};
window.addEventListener("DOMContentLoaded",()=>{
  const search=document.getElementById("search"),crumbs=document.getElementById("crumbs"),focusBox=document.getElementById("focus"),childrenBox=document.getElementById("children"),pager=document.getElementById("pager"),status=document.getElementById("status"),map=document.getElementById("map"),edges=document.getElementById("edges");
  let current=tree,page=0;const size=36,all=[];
  const kind=n=>n.kind==="directory"?"Module":n.kind==="file"?"Source file":"Function";
  const subtitle=n=>n.kind==="function"?"Lines "+n.line+"–"+n.end:n.children?.length? n.children.length+" inside":"No nested source items";
  const norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,"");
  function index(node,parent){node.parent=parent;all.push(node);(node.children||[]).forEach(child=>index(child,node));}index(tree,null);
  function button(label,action,cls=""){const b=document.createElement("button");b.textContent=label;b.className=cls;b.addEventListener("click",action);return b;}
  function learn(node){status.textContent="Preparing "+node.name+"…";window.regainApi.postMessage({type:"prepareScope",path:node.path,symbol:node.kind==="function"?node.name:"",line:node.line||0,end:node.end||0});}
  function explore(node){current=node;page=0;search.value="";render();}
  function card(node,isFocus){const el=document.createElement("article");el.className="card";const tag=document.createElement("div");tag.className="tag";tag.textContent=isFocus?"Selected · "+kind(node):kind(node);el.append(tag);const heading=document.createElement(isFocus?"h2":"h3");heading.textContent=node.name;el.append(heading);const info=document.createElement("p");info.textContent=subtitle(node);el.append(info);const actions=document.createElement("div");actions.className="actions";actions.append(button("Learn this "+(node.kind==="directory"?"branch":node.kind==="file"?"file":"function"),()=>learn(node),"learn"));if(node.children?.length&&!isFocus)actions.append(button("Explore →",()=>explore(node)));el.append(actions);return el;}
  function drawEdges(){edges.innerHTML="";if(matchMedia("(max-width:700px)").matches)return;const base=map.getBoundingClientRect(),from=focusBox.querySelector(".card")?.getBoundingClientRect();if(!from)return;for(const target of childrenBox.querySelectorAll(".card")){const to=target.getBoundingClientRect();const x1=from.right-base.left,y1=from.top+from.height/2-base.top,x2=to.left-base.left,y2=to.top+to.height/2-base.top;const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d","M "+x1+" "+y1+" C "+(x1+x2)/2+" "+y1+", "+(x1+x2)/2+" "+y2+", "+x2+" "+y2);p.setAttribute("fill","none");p.setAttribute("stroke","var(--edge)");p.setAttribute("stroke-width","2");edges.append(p);}}
  function render(){const query=norm(search.value);const results=query?all.filter(n=>n!==tree&&norm(n.name).includes(query)):current.children||[];focusBox.replaceChildren(card(current,true));childrenBox.replaceChildren();crumbs.replaceChildren();const chain=[];for(let n=current;n;n=n.parent)chain.unshift(n);chain.forEach((n,i)=>{if(i){const sep=document.createElement("span");sep.textContent="›";crumbs.append(sep);}crumbs.append(button(n.name,()=>explore(n)));});const total=Math.ceil(results.length/size);page=Math.min(page,Math.max(0,total-1));for(const node of results.slice(page*size,(page+1)*size))childrenBox.append(card(node,false));if(!results.length){const empty=document.createElement("p");empty.className="empty";empty.textContent=query?"No matching module, file, or function.":"No deeper source items. Select Learn to cover this item.";childrenBox.append(empty);}pager.replaceChildren();if(total>1){pager.append(button("← Previous",()=>{page--;render();}));const label=document.createElement("span");label.textContent=(page+1)+" / "+total;pager.append(label);pager.append(button("Next →",()=>{page++;render();}));}requestAnimationFrame(drawEdges);}
  search.addEventListener("input",()=>{page=0;render();});new ResizeObserver(drawEdges).observe(map);render();
});
</script></body></html>`;
}

module.exports = {diagramPage};
