const fs = require("fs");
const path = require("path");
const {showAnalyzing} = require("./semantic-map");

function setupRequest(root, focus) {
  return `# ReGain setup request\n\n<!-- generated by ReGain; review this request before sending it to an agent -->\n\nPlease create a useful ReGain walkthrough for this project.\n\nProject folder: ${root}\nFocus: ${focus || "the whole project"}\n\nRead the actual source, nearby documentation, and entry points before writing. If the scope is large, focus on the main execution path and state what is outside scope. Existing .regain/ pages may be empty templates; replace those with verified content.\n\nWrite inside .regain/:\n\n1. overview.md: explain the goal and stages, include a Mermaid flow diagram, and link each stage to source files.\n2. understanding.md: record the verified entry points, call flow, important decisions, dependencies, details that are easy to miss, and unresolved questions. Cite project-relative files for claims.\n3. A descriptive *.regain.md walkthrough: show real files in execution order using \`\`\`file path/to/file\`\`\` blocks, with short explanations and small runnable Python cells where practical. State the environment needed.\n4. Run .regain/tooling/build_general_importance.py from the project root. Review the important decision lines, add hash-bound corrections to .regain/importance-reviews.json, and regenerate the map. If this cannot run, document why.\n\nPreserve application code and user data. Do not run large datasets, training, or long evaluations. Explain what you verified and what remains uncertain.\n`;
}

async function setupProject(root, extensionPath, focus, empty = false) {
  const regain = path.join(root, ".regain");
  const tooling = path.join(regain, "tooling");
  await fs.promises.mkdir(tooling, {recursive: true});
  const created = [];
  const bundled = path.join(extensionPath, "resources", "tooling");
  for (const file of ["build_general_importance.py", "cpp_importance.py"]) {
    const source = path.join(bundled, file);
    if (!fs.existsSync(source)) throw new Error(`Bundled ReGain tool is missing: ${file}`);
    try { await fs.promises.copyFile(source, path.join(tooling, file), fs.constants.COPYFILE_EXCL); created.push(`tooling/${file}`); }
    catch (error) { if (error.code !== "EEXIST") throw error; }
  }
  if (empty) return {created, regain};
  const existingOverview = path.join(regain, "overview.html");
  let overviewPath = existingOverview;
  try {
    const previous = await fs.promises.readFile(existingOverview, "utf8");
    if (!previous.includes("REGAIN_SEMANTIC_V1")) overviewPath = await showAnalyzing(root);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
    overviewPath = await showAnalyzing(root);
  }
  return {created: created.concat("overview.html"), regain, overviewPath};
}

module.exports = {setupProject, setupRequest};
