const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"}[char]));

function semanticDiagram(map) {
  const data = JSON.stringify(map).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
  return `<!doctype html><!-- REGAIN_SEMANTIC_V1 -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(map.projectName)} · ReGain</title>
<style>
:root{font-family:Inter,Segoe UI,system-ui,sans-serif;color-scheme:dark;background:#0d1721;color:#eef6f8;--panel:#192a37;--edge:#395667;--muted:#a6bfcb;--accent:#78dade;--accent2:#adbaff}
:root[data-theme="light"]{color-scheme:light;background:#f4f8fa;color:#19303b;--panel:#fff;--edge:#c9dce5;--muted:#506b79;--accent:#087d86;--accent2:#585fa2}
*{box-sizing:border-box}body{margin:0;padding:clamp(20px,4vw,48px)}main{max-width:1250px;margin:auto}.eyebrow{font-size:.75rem;letter-spacing:.15em;text-transform:uppercase;font-weight:800;color:var(--accent)}h1{font-size:clamp(2.1rem,4vw,3.5rem);margin:12px 0}.summary{max-width:820px;color:var(--muted);line-height:1.6;font-size:1.08rem}h2{font-size:1.35rem;margin:34px 0 15px}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:23px 0}input{flex:1;min-width:min(340px,100%);border:1px solid var(--edge);background:var(--panel);color:inherit;border-radius:10px;padding:11px 14px;font:inherit}input:focus{outline:2px solid var(--accent)}.map{display:grid;grid-template-columns:minmax(245px,310px) minmax(0,1fr);gap:32px;align-items:start}.capabilities{display:grid;gap:10px;max-height:70vh;overflow:auto;padding-right:4px}.cap{display:block;width:100%;text-align:left;background:var(--panel);color:inherit;border:1px solid var(--edge);border-radius:12px;padding:15px;cursor:pointer}.cap:hover,.cap[aria-selected=true]{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}.cap strong{display:block;font-size:1rem}.cap small{color:var(--muted);display:block;margin-top:6px;line-height:1.4}.badge{display:inline-block;color:var(--accent);font-size:.7rem;font-weight:750;text-transform:uppercase;letter-spacing:.09em;margin-bottom:7px}.detail{background:var(--panel);border:1px solid var(--edge);border-radius:18px;padding:clamp(18px,3vw,28px);min-height:250px}.detail h2{font-size:1.8rem;margin:0 0 10px}.detail p{color:var(--muted);line-height:1.55}.flow{display:flex;flex-wrap:wrap;gap:10px;align-items:stretch;margin:25px 0}.stage{flex:1 1 175px;border:1px solid var(--edge);border-radius:12px;padding:15px;min-width:175px;position:relative}.stage:not(:last-child):after{content:"→";position:absolute;right:-12px;top:40%;color:var(--accent);font-size:1.2rem;z-index:1}.stage strong{display:block;margin:8px 0}.stage p{font-size:.83rem;margin:0}.num{color:var(--accent);font-size:.72rem;font-weight:850;letter-spacing:.1em}.sources{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0}.sources a{font-size:.8rem;color:var(--accent);border:1px solid var(--edge);border-radius:999px;padding:5px 8px;text-decoration:none;max-width:100%;overflow-wrap:anywhere}.sources a:hover{text-decoration:underline}.relation{font-size:.84rem;color:var(--muted)}.deep{border:1px solid var(--accent);background:color-mix(in srgb,var(--accent) 10%,transparent);border-radius:9px;color:var(--accent);padding:10px 14px;font:inherit;cursor:pointer}.deep:hover{background:color-mix(in srgb,var(--accent) 20%,transparent)}#status{min-height:23px;color:var(--accent);font-size:.85rem}.uncertain{font-size:.85rem;color:var(--muted);border-top:1px solid var(--edge);margin-top:30px;padding-top:15px}@media(max-width:800px){.map{grid-template-columns:1fr}.capabilities{display:flex;overflow:auto;max-height:none}.cap{min-width:215px}.stage:after{display:none}}
</style></head><body><main><div class="eyebrow">ReGain · how this project works</div><h1>${escapeHtml(map.projectName)}</h1><p class="summary">${escapeHtml(map.summary)}</p><div class="toolbar"><input id="search" type="search" placeholder="Find a capability…" aria-label="Find a capability"></div><div class="map"><div class="capabilities" id="capabilities"></div><section class="detail" id="detail" aria-live="polite"></section></div><div id="status" role="status"></div><section class="uncertain" id="uncertain"></section></main>
<script>
const map=${data};
window.addEventListener("DOMContentLoaded",()=>{
  const list=document.getElementById("capabilities"),detail=document.getElementById("detail"),search=document.getElementById("search"),status=document.getElementById("status"),uncertain=document.getElementById("uncertain");let selected=map.capabilities[0];
  function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
  function sourceLink(path,reason){const a=el("a",path);a.href="../"+path;a.title=reason||path;return a;}
  function show(cap){selected=cap;detail.replaceChildren();detail.append(el("span",cap.runtimeStatus,"badge"),el("h2",cap.name),el("p",cap.purpose));const flow=el("div",undefined,"flow");cap.flow.forEach((step,i)=>{const card=el("article",undefined,"stage");card.append(el("span",String(i+1).padStart(2,"0"),"num"),el("strong",step.label),el("p",step.description));const refs=el("div",undefined,"sources");step.sources.forEach(path=>refs.append(sourceLink(path,path)));card.append(refs);flow.append(card);});detail.append(flow);const refs=el("div",undefined,"sources");cap.sources.forEach(item=>refs.append(sourceLink(item.path,item.reason)));detail.append(el("h3","Source evidence"),refs);if(cap.related.length)detail.append(el("p","Related capabilities: "+cap.related.map(id=>map.capabilities.find(item=>item.id===id)?.name||id).join(", "),"relation"));const deep=el("button","Analyze this capability in detail","deep");deep.addEventListener("click",()=>{status.textContent="Agent analyzing "+cap.name+"…";window.regainApi.postMessage({type:"analyzeCapability",id:cap.id});});detail.append(deep);renderList();}
  function renderList(){const query=search.value.toLowerCase().replace(/[^a-z0-9]+/g,"");list.replaceChildren();for(const cap of map.capabilities){if(query&&!((cap.name+" "+cap.purpose).toLowerCase().replace(/[^a-z0-9]+/g,"").includes(query)))continue;const card=el("button",undefined,"cap");card.setAttribute("aria-selected",String(cap===selected));card.append(el("span",cap.runtimeStatus,"badge"),el("strong",cap.name),el("small",cap.purpose));card.addEventListener("click",()=>show(cap));list.append(card);}if(!list.children.length)list.append(el("p","No matching capability."));}
  search.addEventListener("input",renderList);uncertain.textContent=map.uncertainties.length?"Unresolved: "+map.uncertainties.join(" · "):"The agent found source evidence for each capability shown.";show(selected);
});
</script></body></html>`;
}

module.exports = {semanticDiagram};
